name: microspat
dependencies:
    - python=2.7
    - scipy
    - numpy
    - flask
    - greenlet
    - sqlalchemy
    - pip:
        - sklearn
        - flask-sqlalchemy
        - flask-socketio
        - flask-script
        - flask-migrate
        - eventlet
        - dill
        - pathos
