import { NgModule } from '@angular/core';
import { MatButtonModule,
         MatCheckboxModule,
         MatMenuModule,
         MatChipsModule,
         MatCardModule,
         MatGridListModule,
         MatTabsModule,
         MatSelectModule,
         MatProgressSpinnerModule,
         MatProgressBarModule,
         MatListModule,
         MatFormFieldModule,
         MatInputModule,
         MatDividerModule,
         MatTableModule,
         MatSortModule } from '@angular/material';

@NgModule({
  imports: [
    MatButtonModule,
    MatCheckboxModule,
    MatMenuModule,
    MatChipsModule,
    MatCardModule,
    MatGridListModule,
    MatTabsModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatListModule,
    MatFormFieldModule,
    MatInputModule,
    MatDividerModule,
    MatTableModule,
    MatSortModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatMenuModule,
    MatChipsModule,
    MatCardModule,
    MatGridListModule,
    MatTabsModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatListModule,
    MatFormFieldModule,
    MatInputModule,
    MatDividerModule,
    MatTableModule,
    MatSortModule
  ],
})
export class MspatMaterialModule { }
